### ISSUE TITLE
Cannot build two extensions (xk6-git and xk6-output-prometheus-remote) together

### ISSUE THREAD

**Issue by emzxcv** [grafana/xk6#94] opened 2024-03-26 04:49 UTC
```
docker run --rm -e GOOS=darwin -u "$(id -u):$(id -g)" -v "${PWD}:/xk6" \
  grafana/xk6 build \
  --with github.com/skibum55/xk6-git \
  --with github.com/grafana/xk6-output-prometheus-remote
```

I'm trying to build this but it seems to have an error such as
```
go: k6 imports
        github.com/skibum55/xk6-git imports
        go.k6.io/k6/js/modules imports
        go.k6.io/k6/loader tested by
        go.k6.io/k6/loader.test imports
        go.k6.io/k6/lib/testutils/httpmultibin imports
        google.golang.org/grpc/status imports
        google.golang.org/genproto/googleapis/rpc/status: ambiguous import: found package google.golang.org/genproto/googleapis/rpc/status in multiple modules:
        google.golang.org/genproto v0.0.0-20210226172003-ab064af71705 (/go/pkg/mod/google.golang.org/genproto@v0.0.0-20210226172003-ab064af71705/googleapis/rpc/status)
        google.golang.org/genproto/googleapis/rpc v0.0.0-20230525234030-28d5490b6b19 (/go/pkg/mod/google.golang.org/genproto/googleapis/rpc@v0.0.0-20230525234030-28d5490b6b19/status)
```
        
  I have tried 
       ```
         --replace=google.golang.org/genproto=google.golang.org/genproto@v0.0.0-20230525234030-28d5490b6b19
         ```
 but to no luck. Any help would be appreciated!

**Comment by pablochacin** [comment] 2024-07-04 12:36
@emzxcv I ran the same docker command and I cannot reproduce the error. I think this error was fixed in a newer version of k6. Could you please try again?

**Comment by pablochacin** [comment] 2024-07-29 09:20
closing. No answer from author.

**Closed by pablochacin** 2024-07-29 09:20 UTC
